### ISSUE TITLE
Licensing.

### ISSUE THREAD

**Issue by HypertextPP** [BedrockJS/RakNet#1]
As you should be aware, [Bedrock.js](https://github.com/BradW/Bedrock.js) is licensed under the GNU General Public License v3.0. This repository includes material from that project and should therefore also be licensed under GPL v3.

I kindly request that you add the [original LICENSE](https://github.com/BradW/Bedrock.js/blob/master/LICENSE) file to this repository.

**Comment by Olybear9** [comment]
Thanks, forgot to add when creating repository.
